[phases.setup]
nixPkgs = [
  "ffmpeg",
  "pkg-config",
  "libsodium",
  "libopus",
  "python311",
  "bash"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  "chmod +x start.sh"
]

[start]
cmd = "./start.sh"
