[phases.setup]
nixPkgs = [
  "ffmpeg",
  "pkg-config",
  "libsodium",
  "libopus",
  "python311"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && LD_LIBRARY_PATH=/nix/var/nix/profiles/default/lib python main.py"
